#############################################################################
# Makefile for building: PingTest
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  PingTest.pro
# Template: app
# Command: /usr/lib/Qt5.5.0/5.5/gcc_64/bin/qmake -o Makefile PingTest.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/lib/Qt5.5.0/5.5/gcc_64/include -I/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets -I/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui -I/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore -I. -I/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/lib/Qt5.5.0/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PingTest1.0.0
DISTDIR = /home/frederick/MyCode/PingTest/.tmp/PingTest1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/Qt5.5.0/5.5/gcc_64 -Wl,-rpath,/usr/lib/Qt5.5.0/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/lib/Qt5.5.0/5.5/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Window.cpp 
OBJECTS       = main.o \
		Window.o
DIST          = /usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/linux.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/qconfig.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_post.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resources.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/moc.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/uic.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/yacc.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/lex.prf \
		PingTest.pro  main.cpp \
		Window.cpp
QMAKE_TARGET  = PingTest
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = PingTest


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PingTest.pro /usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/linux.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/qconfig.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_post.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resources.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/moc.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/uic.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/yacc.prf \
		/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/lex.prf \
		PingTest.pro \
		/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Widgets.prl \
		/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Gui.prl \
		/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile PingTest.pro
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/unix.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/linux.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/sanitize.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-base.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/qconfig.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt_config.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/spec_post.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_pre.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/default_post.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/warn_on.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/qt.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/resources.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/moc.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/uic.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/exceptions.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/yacc.prf:
/usr/lib/Qt5.5.0/5.5/gcc_64/mkspecs/features/lex.prf:
PingTest.pro:
/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Widgets.prl:
/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Gui.prl:
/usr/lib/Qt5.5.0/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PingTest.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Window.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) PingTest  

distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/QApplication \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qglobal.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qconfig.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfeatures.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlogging.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qflags.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmutex.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qnumeric.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstring.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qchar.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbytearray.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qrefcount.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qnamespace.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobject.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringlist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qregexp.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmetatype.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qisenum.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qeventloop.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qpoint.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsize.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qcursor.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmargins.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qrect.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpalette.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qcolor.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qrgb.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qbrush.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qpair.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvector.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qmatrix.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpolygon.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qregion.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qdatastream.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qiodevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qline.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qtransform.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qimage.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpixmap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qshareddata.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qhash.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfont.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qevent.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvariant.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qdebug.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtextstream.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qset.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qurl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qurlquery.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfile.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qvector2d.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qinputmethod.h \
		Window.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/QWidget \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/QPushButton \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Window.o: Window.cpp Window.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/QWidget \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qglobal.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qconfig.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfeatures.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlogging.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qflags.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmutex.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qnumeric.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qnamespace.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobject.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstring.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qchar.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbytearray.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qrefcount.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringlist.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qregexp.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmetatype.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qisenum.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmargins.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qrect.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsize.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qpoint.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpalette.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qcolor.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qrgb.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qbrush.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qpair.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvector.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qmatrix.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpolygon.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qregion.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qdatastream.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qiodevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qline.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qtransform.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qimage.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qpixmap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qshareddata.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qhash.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfont.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qcursor.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qevent.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qvariant.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qmap.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qdebug.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qtextstream.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qset.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qurl.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qurlquery.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfile.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qvector2d.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/QPushButton \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		/usr/lib/Qt5.5.0/5.5/gcc_64/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o Window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

