######################################################################
# Automatically generated by qmake (3.0) Wed Jul 1 23:27:30 2015
######################################################################

TEMPLATE = app
TARGET = PingTest
INCLUDEPATH += .
QT += core gui
QT += widgets

# Input
HEADERS += 
SOURCES += main.cpp Window.cpp
